// ================================================================
// TibiaPedia v3 — Game Data
// Wiki image helper: all creature/item images from TibiaWiki
// ================================================================
const WIKI_IMG = name => `https://tibia.fandom.com/wiki/Special:Redirect/file/${encodeURIComponent(name.replace(/ /g,'_'))}.gif`;
const TIBIA_IMG = race => `https://static.tibia.com/images/library/${encodeURIComponent(race)}.gif`;

// Element definitions with Tibia-style display
const ELEMENTS = [
  {key:'physical',name:'Physical',abbr:'Phy',css:'physical'},
  {key:'fire',name:'Fire',abbr:'Fir',css:'fire'},
  {key:'ice',name:'Ice',abbr:'Ice',css:'ice'},
  {key:'energy',name:'Energy',abbr:'Ene',css:'energy'},
  {key:'earth',name:'Earth',abbr:'Ear',css:'earth'},
  {key:'holy',name:'Holy',abbr:'Hol',css:'holy'},
  {key:'death',name:'Death',abbr:'Dea',css:'death'},
  {key:'drown',name:'Drown',abbr:'Drw',css:'drown'},
  {key:'hpDrain',name:'Life Drain',abbr:'HP',css:'lifedrain'},
  {key:'heal',name:'Heal',abbr:'Hea',css:'manadrain'}
];

// Slot icons (wiki item names for images)
const SLOT_META = {
  helmet:{label:'Helmet',img:'Helmet_Slot'},
  armor:{label:'Armor',img:'Armor_Slot'},
  legs:{label:'Legs',img:'Legs_Slot'},
  boots:{label:'Boots',img:'Boots_Slot'},
  shield:{label:'Shield/Spellbook',img:'Shield_Slot'},
  weapon:{label:'Weapon',img:'Weapon_Slot'},
  ring:{label:'Ring',img:'Ring_Slot'},
  amulet:{label:'Amulet',img:'Amulet_Slot'}
};

// Cities for map
const CITIES = [
  {name:"Thais",cx:32369,cy:32241},{name:"Carlin",cx:32360,cy:31782},
  {name:"Venore",cx:32957,cy:32076},{name:"Ab'Dendriel",cx:32682,cy:31639},
  {name:"Kazordoon",cx:32631,cy:31925},{name:"Ankrahmun",cx:33162,cy:32688},
  {name:"Darashia",cx:33224,cy:32432},{name:"Edron",cx:33217,cy:31814},
  {name:"Port Hope",cx:32623,cy:32753},{name:"Liberty Bay",cx:32317,cy:32826},
  {name:"Svargrond",cx:32267,cy:31131},{name:"Yalahar",cx:32792,cy:31274},
  {name:"Rathleton",cx:33594,cy:31899},{name:"Roshamuul",cx:33513,cy:32363},
  {name:"Issavi",cx:33921,cy:31428},{name:"Feyrist",cx:33558,cy:32224},
  {name:"Rookgaard",cx:32097,cy:32205},{name:"Dawnport",cx:32070,cy:31932}
];

// ================================================================
// HUNTING SPOTS (expanded with routes, access, recommended gear)
// ================================================================
const HUNTING_SPOTS = [
{name:"Rotworm Caves",city:"Darashia",level:[8,25],voc:["knight","paladin","sorcerer","druid"],exp:3,loot:2,
  creatures:["Rotworm","Carrion Worm"],cx:33220,cy:32430,
  route:"From Darashia depot, head west past the magic carpet. Go south into the desert. Find the hole and rope down.",
  access:"None — free access.",
  gear:"Plate Armor, Plate Legs, any weapon. Bring rope and shovel.",
  tips:"Great for new players. Rotworms drop gold and maces regularly."},
{name:"Tarantula Caves",city:"Port Hope",level:[15,35],voc:["knight","paladin"],exp:3,loot:3,
  creatures:["Tarantula"],cx:32600,cy:32740,
  route:"From Port Hope depot, go east over the bridge, then south into the jungle. The cave entrance is on the eastern side.",
  access:"None — free access.",
  gear:"Steel Helmet, Plate Armor. Bring health potions.",
  tips:"Good early profit from spider silk. Knights can solo easily."},
{name:"Cyclopolis",city:"Edron",level:[25,45],voc:["knight","paladin","sorcerer","druid"],exp:3,loot:3,
  creatures:["Cyclops","Cyclops Smith","Cyclops Drone"],cx:33290,cy:31710,
  route:"From Edron depot, head north past the castle. Cross the bridge east and follow the path to the mountain cave.",
  access:"None — free access.",
  gear:"Royal Helmet, Plate Armor or better. Knights: sword/axe with good defense shield.",
  tips:"Cyclops Smiths drop heavy items worth good gold. Bring a shovel."},
{name:"Amazon Camp",city:"Venore",level:[15,30],voc:["knight","paladin","sorcerer","druid"],exp:2,loot:3,
  creatures:["Amazon","Valkyrie","Witch"],cx:32820,cy:32620,
  route:"From Venore depot, head south through the swamp. Cross the bridge and continue south to the camp.",
  access:"None — free access.",
  gear:"Scale Armor, basic weapon. Bring antidote potions.",
  tips:"Great loot for low levels — protective charms and small valuables."},
{name:"Mintwallin",city:"Thais",level:[8,20],voc:["knight","paladin","sorcerer","druid"],exp:2,loot:2,
  creatures:["Minotaur","Minotaur Archer","Minotaur Guard"],cx:32400,cy:32100,
  route:"From Thais depot, go north through the city gate. Follow the road north and find the sewer entrance or go to the cave system.",
  access:"None — free access.",
  gear:"Chain Armor, basic weapon.",
  tips:"Classic early game spot. Guards can hit hard — be careful at low level."},
{name:"Dragon Lair",city:"Darashia",level:[45,70],voc:["knight","paladin"],exp:4,loot:4,
  creatures:["Dragon"],cx:33190,cy:32410,
  route:"From Darashia depot, head north to the mountain. Rope up the cliff and find the cave entrance on the plateau.",
  access:"None — bring rope and be prepared for fire damage.",
  gear:"Crown/Royal Helmet, Magic Plate Armor, fire protection shield. Fire resistance equipment highly recommended.",
  tips:"Dragons drop Dragon Hammers and Shields worth 4-8k each. Bring fire walls for mages. Knights should have 70+ skills."},
{name:"Wyrm Mountain",city:"Liberty Bay",level:[80,120],voc:["knight","paladin","sorcerer","druid"],exp:4,loot:3,
  creatures:["Wyrm","Elder Wyrm"],cx:32330,cy:32860,
  route:"From Liberty Bay, take the boat to the islands. Head to the wyrm mountain on the main island.",
  access:"None — boat ticket required.",
  gear:"Zaoan Helmet, Prismatic Armor, physical protection.",
  tips:"Elder Wyrms hit harder but give much better XP. Good for bestiary."},
{name:"Drefia Grim Reapers",city:"Darashia",level:[120,200],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:4,
  creatures:["Grim Reaper","Nightmare"],cx:33160,cy:32490,
  route:"From Darashia, head south to Drefia. Navigate the underground corridors to the Grim Reaper area.",
  access:"Drefia access — need to complete a short mission series.",
  gear:"Death protection equipment (Foxtail Amulet, physical protection set).",
  tips:"One of the best solo spots for paladins 130-200. Use energy walls."},
{name:"Edron Hero Cave",city:"Edron",level:[70,100],voc:["knight","paladin"],exp:4,loot:3,
  creatures:["Hero","Vile Grandmaster"],cx:33260,cy:31700,
  route:"From Edron depot, head far south past the academy. The cave entrance is in the mountain.",
  access:"None — free access.",
  gear:"Magic Plate Armor, Boots of Haste, fire/energy protection.",
  tips:"Heroes can combo hard. Approach carefully and use full HP."},
{name:"Upper Spike",city:"Kazordoon",level:[50,80],voc:["knight","druid"],exp:3,loot:3,
  creatures:["Wyvern","Corym Vanguard","Corym Skirmisher"],cx:32580,cy:31900,
  route:"From Kazordoon depot, take the mine cart system down. Follow signs to the Spike entrance.",
  access:"Spike Tasks Quest — talk to gnome NPCs in Kazordoon.",
  gear:"Physical protection set, Fire Axe/Bright Sword.",
  tips:"Good team spot. Druids heal knight, knight blocks coryms."},
{name:"Krailos Steppe",city:"Edron",level:[60,100],voc:["knight","paladin","druid"],exp:4,loot:3,
  creatures:["Ogre Brute","Ogre Savage","Ogre Shaman"],cx:33540,cy:31610,
  route:"From Edron, take the boat/teleport to Krailos. The steppe is on the surface.",
  access:"None after reaching Krailos.",
  gear:"Physical protection, good armor.",
  tips:"Ogres have high physical damage. Earth protection helps for shamans."},
{name:"Werehyaena Caves",city:"Edron",level:[80,130],voc:["knight","paladin","sorcerer","druid"],exp:4,loot:4,
  creatures:["Werehyaena","Werehyaena Shaman"],cx:33500,cy:31650,
  route:"From Edron, travel east to Grimvale. The werehyaena caves are in the northern part.",
  access:"Grimvale access — short mission from Edron NPCs.",
  gear:"Physical protection, Silver Token equipment.",
  tips:"Only accessible during full moon phases. Amazing loot (Foxtail Amulets)."},
{name:"Ghastly Dragons",city:"Zao",level:[130,200],voc:["knight","paladin"],exp:5,loot:4,
  creatures:["Ghastly Dragon"],cx:33290,cy:31150,
  route:"From Zao outpost, head deep into the steppe. Enter the underground and follow the dragon tunnels.",
  access:"The New Frontier + Children of the Revolution quests required.",
  gear:"Death protection (Foxtail Amulet), Zaoan equipment, Terra Boots.",
  tips:"One of the best solo spots for knights 130-180. Very profitable."},
{name:"Lizard City",city:"Zao",level:[100,150],voc:["knight","paladin","sorcerer","druid"],exp:4,loot:4,
  creatures:["Lizard High Guard","Lizard Legionnaire","Lizard Dragon Priest"],cx:33300,cy:31200,
  route:"From Zao outpost, head south through the steppe into the city ruins.",
  access:"The New Frontier + Children of the Revolution quests.",
  gear:"Zaoan Helmet, Zaoan Legs, fire protection for Dragon Priests.",
  tips:"Dragon Priests heal others — target them first. Great XP and gold."},
{name:"Oramond Minos",city:"Rathleton",level:[180,300],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:5,
  creatures:["Minotaur Amazon","Minotaur Hunter","Execowtioner","Mooh'tah Warrior"],cx:33650,cy:31910,
  route:"From Rathleton depot, take the underground system south to Oramond. Enter the Minotaur area.",
  access:"Oramond Quest — need 40 daily task completions (voting/tasks) to unlock Mino area!",
  gear:"Prismatic Armor, Zaoan Helmet, physical protection, fire protection for Execowtioners.",
  tips:"THE BEST PROFIT in the game for 200-300 range. Worth grinding 40 tasks to unlock. Expect 500k-1kk+ gold/hour."},
{name:"Glooth Bandits",city:"Rathleton",level:[150,250],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:5,
  creatures:["Glooth Bandit"],cx:33660,cy:31900,
  route:"From Rathleton, head to the Oramond underground. Glooth Bandits area is before the Minos.",
  access:"Oramond Quest — basic access (fewer tasks than Minos).",
  gear:"Physical protection set, good weapon.",
  tips:"Very good profit and XP. Easier access than Minos."},
{name:"Asura Palace",city:"Port Hope",level:[150,250],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:5,
  creatures:["Asura","Dawnfire Asura","Midnight Asura","True Midnight Asura"],cx:32620,cy:32760,
  route:"From Port Hope, head south into the jungle. Navigate to the underground palace entrance.",
  access:"Short access quest from Port Hope NPCs.",
  gear:"Energy protection for Midnight Asuras, fire protection for Dawnfire.",
  tips:"Excellent loot and XP. Midnight Asuras drop valuable items. Very popular spot."},
{name:"Frost Dragons",city:"Svargrond",level:[80,130],voc:["knight","paladin"],exp:4,loot:4,
  creatures:["Frost Dragon"],cx:32350,cy:31050,
  route:"From Svargrond, take the boat to Okolnir island. The frost dragons are in the ice caves.",
  access:"The Ice Islands Quest required for Okolnir access.",
  gear:"Energy protection ring, fire weapon for damage bonus. Ice protection armor.",
  tips:"Great solo spot for knights 90-130. Frost Dragons drop valuable items."},
{name:"Draken Walls",city:"Zao",level:[130,200],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:4,
  creatures:["Draken Spellweaver","Draken Elite","Draken Abomination"],cx:33340,cy:31230,
  route:"From Zao, navigate through the deeper dragon areas to reach the Draken fortress.",
  access:"Wrath of the Emperor Quest required.",
  gear:"Fire protection (Draken Spellweavers), physical protection set.",
  tips:"One of the best team hunting spots for 150-200. Amazing XP."},
{name:"Roshamuul Prison",city:"Roshamuul",level:[200,300],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:5,
  creatures:["Guzzlemaw","Frazzlemaw","Silencer"],cx:33530,cy:32400,
  route:"From Roshamuul dock, navigate the demon-infested terrain to the prison entrance.",
  access:"Roshamuul Quest required.",
  gear:"Physical protection, death protection, energy protection.",
  tips:"Top-tier XP for teams 250+. Guzzlemaws hit extremely hard."},
{name:"Falcon Bastion",city:"Edron",level:[250,400],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:5,
  creatures:["Falcon Knight","Falcon Paladin"],cx:33330,cy:31700,
  route:"From Edron, head to the Falcon area east of the city. Enter the bastion.",
  access:"Grave Danger Quest required.",
  gear:"Falcon equipment (if available), physical protection, fire protection.",
  tips:"Drops Falcon equipment — second-best tier in game. Very profitable for 300+ teams."},
{name:"Cobra Bastion",city:"Issavi",level:[250,400],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:5,
  creatures:["Cobra Assassin","Cobra Scout","Cobra Vizier"],cx:33910,cy:31440,
  route:"Travel to Issavi on the Kilmaresh continent. The bastion is northeast of the city.",
  access:"Cobra Bastion Quest required (Kilmaresh access).",
  gear:"Cobra Hood, physical protection, earth protection.",
  tips:"Drops Cobra equipment including the coveted Cobra Hood (ML +2)."},
{name:"Secret Library",city:"Various",level:[250,400],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:5,
  creatures:["Burning Book","Icecold Book","Energized Raging Mage"],cx:32760,cy:32750,
  route:"Access through various portals after completing the Secret Library Quest.",
  access:"Secret Library Quest required.",
  gear:"Rotation of fire/ice/energy protection depending on wing.",
  tips:"Best XP/h in the game for 300+. Drops Fabulous Legs (Speed +12)."},
{name:"Flimsy Lost Souls",city:"Darashia",level:[250,400],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:5,
  creatures:["Flimsy Lost Soul","Mean Lost Soul","Freakish Lost Soul"],cx:33200,cy:32450,
  route:"From Darashia, access the soul spawns underground.",
  access:"Feaster of Souls Quest required.",
  gear:"Physical protection, death protection (rotation).",
  tips:"Top-tier XP and profit for 300+ characters."},
{name:"Summer Court",city:"Feyrist",level:[150,250],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:4,
  creatures:["Pixie","Faun","Swan Maiden","Nymph"],cx:33560,cy:32220,
  route:"Enter Feyrist through the fairy portal near Carlin/Ab'Dendriel.",
  access:"A Threatened Dream Quest required.",
  gear:"Physical protection, holy protection for some creatures.",
  tips:"Beautiful area with good XP. Feyrist creatures can heal each other."},
{name:"Winter Court",city:"Feyrist",level:[150,250],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:4,
  creatures:["Boar Man","Dark Faun","Twisted Pooka"],cx:33570,cy:32230,
  route:"From Summer Court, navigate to the Winter section of Feyrist.",
  access:"A Threatened Dream Quest required.",
  gear:"Physical protection, ice protection for some creatures.",
  tips:"Harder than Summer Court but better XP. Watch for Boar Man combos."},
{name:"Grimvale Full Were",city:"Edron",level:[130,200],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:5,
  creatures:["Wereboar","Werebadger","Werefox","Werewolf","Werebear"],cx:33510,cy:31660,
  route:"From Edron, head east to Grimvale. Deep floors have all were-creatures.",
  access:"Grimvale access + full moon phase.",
  gear:"Silver Token equipment, physical protection.",
  tips:"Only during full moon. Best loot from were-creatures — Foxtail Amulets, Werewolf Helmets."},
{name:"Demon Forge",city:"Goroma",level:[200,350],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:5,
  creatures:["Demon","Fire Devil","Dark Torturer"],cx:32350,cy:32530,
  route:"Travel to Goroma island by boat. Navigate through the volcanic terrain.",
  access:"None after reaching Goroma.",
  gear:"Fire protection essential, physical protection.",
  tips:"Classic demon hunting spot. Demons can combo very hard."},
{name:"Ferumbras' Ascendant Tower",city:"Edron",level:[250,400],voc:["knight","paladin","sorcerer","druid"],exp:5,loot:5,
  creatures:["Hellflayer","Vexclaw","Grimeleech"],cx:33280,cy:31720,
  route:"From Edron, enter the tower area accessible after the quest.",
  access:"Ferumbras' Ascension Quest required.",
  gear:"Rotation of protections for different creature types.",
  tips:"Drops destruction-tier weapons. One of the hardest regular spawns."}
];

// ================================================================
// EQUIPMENT DATA (with wiki image names for item graphics)
// ================================================================
const EQUIPMENT = {
knight:{
"8-30":{helmet:{name:"Soldier Helmet",img:"Soldier_Helmet",stats:"Arm: 5",source:"Dwarf Guards, Orc Leaders"},armor:{name:"Plate Armor",img:"Plate_Armor",stats:"Arm: 12",source:"Cyclops, Orc Leaders"},legs:{name:"Plate Legs",img:"Plate_Legs",stats:"Arm: 7",source:"Dragon, Elf Arcanist"},boots:{name:"Leather Boots",img:"Leather_Boots",stats:"Arm: 1",source:"Various creatures"},shield:{name:"Dwarven Shield",img:"Dwarven_Shield",stats:"Def: 26",source:"Dwarf Guard"},weapon:{name:"Bright Sword",img:"Bright_Sword",stats:"Atk: 36, Def: 30",source:"Orc Leaders"},ring:{name:"Life Ring",img:"Life_Ring",stats:"+1 HP/turn",source:"NPC or loot"},amulet:{name:"Protection Amulet",img:"Protection_Amulet",stats:"Physical prot 6%",source:"NPC (100gp)"}},
"30-60":{helmet:{name:"Royal Helmet",img:"Royal_Helmet",stats:"Arm: 9",source:"Behemoths, Quests"},armor:{name:"Blue Robe",img:"Blue_Robe",stats:"Arm: 11, Magic +1",source:"Dragon Lords"},legs:{name:"Crown Legs",img:"Crown_Legs",stats:"Arm: 9",source:"Quests, Dragon Lords"},boots:{name:"Boots of Haste",img:"Boots_of_Haste",stats:"Speed +20",source:"Dragon Lords"},shield:{name:"Demon Shield",img:"Demon_Shield",stats:"Def: 35",source:"Demons"},weapon:{name:"Relic Sword",img:"Relic_Sword",stats:"Atk: 39, Def: 24",source:"Inquisition Quest"},ring:{name:"Life Ring",img:"Life_Ring",stats:"+1 HP/turn",source:"NPC"},amulet:{name:"Platinum Amulet",img:"Platinum_Amulet",stats:"Physical prot 4%",source:"NPC (2000gp)"}},
"60-100":{helmet:{name:"Royal Helmet",img:"Royal_Helmet",stats:"Arm: 9",source:"Behemoths"},armor:{name:"Magic Plate Armor",img:"Magic_Plate_Armor",stats:"Arm: 17",source:"Dragon Lords, Behemoths"},legs:{name:"Golden Legs",img:"Golden_Legs",stats:"Arm: 9",source:"Annihilator Quest"},boots:{name:"Boots of Haste",img:"Boots_of_Haste",stats:"Speed +20",source:"Dragon Lords"},shield:{name:"Blessed Shield",img:"Blessed_Shield",stats:"Def: 40",source:"Inquisition Quest"},weapon:{name:"Magic Longsword",img:"Magic_Longsword",stats:"Atk: 56, Def: 37",source:"Behemoths, Hydras"},ring:{name:"Ring of Healing",img:"Ring_of_Healing",stats:"+2 HP/turn",source:"NPC"},amulet:{name:"Amulet of Loss",img:"Amulet_of_Loss",stats:"No death penalty",source:"NPC"}},
"100-150":{helmet:{name:"Zaoan Helmet",img:"Zaoan_Helmet",stats:"Arm: 9, Sword +1",source:"Lizard City Zao"},armor:{name:"Prismatic Armor",img:"Prismatic_Armor",stats:"Arm: 16, Phys prot 5%",source:"Market"},legs:{name:"Zaoan Legs",img:"Zaoan_Legs",stats:"Arm: 9",source:"Lizard City Zao"},boots:{name:"Guardian Boots",img:"Guardian_Boots",stats:"Arm: 3, Speed +4",source:"Market"},shield:{name:"Ornate Shield",img:"Ornate_Shield",stats:"Def: 38",source:"Market"},weapon:{name:"Shiny Blade",img:"Shiny_Blade",stats:"Atk: 52, Sword +1",source:"Roshamuul"},ring:{name:"Prismatic Ring",img:"Prismatic_Ring",stats:"Phys prot 5%",source:"Market"},amulet:{name:"Foxtail Amulet",img:"Foxtail_Amulet",stats:"+4 Speed",source:"Were creatures"}},
"150-200":{helmet:{name:"Cobra Hood",img:"Cobra_Hood",stats:"Arm: 10, ML +1, Sword +2",source:"Cobra Bastion"},armor:{name:"Prismatic Armor",img:"Prismatic_Armor",stats:"Arm: 16, Phys prot 5%",source:"Market"},legs:{name:"Ornate Legs",img:"Ornate_Legs",stats:"Arm: 10",source:"Oramond Minos"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Arm: 3, Speed +10",source:"Dream Courts"},shield:{name:"Ornate Shield",img:"Ornate_Shield",stats:"Def: 38",source:"Market"},weapon:{name:"Blade of Destruction",img:"Blade_of_Destruction",stats:"Atk: 54, Sword +3",source:"Ferumbras Ascension"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Foxtail Amulet",img:"Foxtail_Amulet",stats:"+4 Speed",source:"Were creatures"}},
"200-300":{helmet:{name:"Falcon Coif",img:"Falcon_Coif",stats:"Arm: 11, Shielding +3",source:"Falcon Bastion"},armor:{name:"Falcon Plate",img:"Falcon_Plate",stats:"Arm: 17, Sword +3",source:"Falcon Bastion"},legs:{name:"Fabulous Legs",img:"Fabulous_Legs",stats:"Arm: 10, Speed +12",source:"Secret Library"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Arm: 3, Speed +10",source:"Dream Courts"},shield:{name:"Falcon Shield",img:"Falcon_Shield",stats:"Def: 41, Shielding +3",source:"Falcon Bastion"},weapon:{name:"Falcon Battleaxe",img:"Falcon_Battleaxe",stats:"Atk: 54, Axe +3",source:"Falcon Bastion"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Enchanted Theurgic Amulet",img:"Enchanted_Theurgic_Amulet",stats:"Phys 2%, ML +2",source:"Forgotten Knowledge"}},
"300+":{helmet:{name:"Falcon Coif",img:"Falcon_Coif",stats:"Arm: 11, Shielding +3",source:"Falcon Bastion"},armor:{name:"Soulmantle",img:"Soulmantle",stats:"Arm: 18, Sword +4",source:"Soul War Quest"},legs:{name:"Soulstrider",img:"Soulstrider",stats:"Arm: 11, Speed +15",source:"Soul War Quest"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Arm: 3, Speed +10",source:"Dream Courts"},shield:{name:"Soulbastion",img:"Soulbastion",stats:"Def: 42, Shielding +4",source:"Soul War Quest"},weapon:{name:"Soulcutter",img:"Soulcutter",stats:"Atk: 55, Sword +4",source:"Soul War Quest"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Enchanted Theurgic Amulet",img:"Enchanted_Theurgic_Amulet",stats:"Phys 2%, ML +2",source:"Forgotten Knowledge"}}
},
paladin:{
"8-30":{helmet:{name:"Soldier Helmet",img:"Soldier_Helmet",stats:"Arm: 5",source:"Dwarf Guards"},armor:{name:"Scale Armor",img:"Scale_Armor",stats:"Arm: 9",source:"Various"},legs:{name:"Plate Legs",img:"Plate_Legs",stats:"Arm: 7",source:"Various"},boots:{name:"Leather Boots",img:"Leather_Boots",stats:"Arm: 1",source:"Various"},shield:{name:"Dwarven Shield",img:"Dwarven_Shield",stats:"Def: 26",source:"Dwarf Guard"},weapon:{name:"Elvish Bow",img:"Elvish_Bow",stats:"Range: 6",source:"Elf Arcanist"},ring:{name:"Life Ring",img:"Life_Ring",stats:"+1 HP/turn",source:"NPC"},amulet:{name:"Protection Amulet",img:"Protection_Amulet",stats:"Phys prot 6%",source:"NPC"}},
"30-60":{helmet:{name:"Royal Helmet",img:"Royal_Helmet",stats:"Arm: 9",source:"Behemoths"},armor:{name:"Paladin Armor",img:"Paladin_Armor",stats:"Arm: 12, Dist +2",source:"Quest"},legs:{name:"Crown Legs",img:"Crown_Legs",stats:"Arm: 9",source:"Quest"},boots:{name:"Boots of Haste",img:"Boots_of_Haste",stats:"Speed +20",source:"Dragon Lords"},shield:{name:"Demon Shield",img:"Demon_Shield",stats:"Def: 35",source:"Demons"},weapon:{name:"Arbalest",img:"Arbalest",stats:"Range: 6, Atk: 49",source:"Market"},ring:{name:"Life Ring",img:"Life_Ring",stats:"+1 HP/turn",source:"NPC"},amulet:{name:"Platinum Amulet",img:"Platinum_Amulet",stats:"Phys prot 4%",source:"NPC"}},
"60-100":{helmet:{name:"Royal Helmet",img:"Royal_Helmet",stats:"Arm: 9",source:"Behemoths"},armor:{name:"Paladin Armor",img:"Paladin_Armor",stats:"Arm: 12, Dist +2",source:"Quest"},legs:{name:"Golden Legs",img:"Golden_Legs",stats:"Arm: 9",source:"Annihilator"},boots:{name:"Boots of Haste",img:"Boots_of_Haste",stats:"Speed +20",source:"Dragon Lords"},shield:{name:"Blessed Shield",img:"Blessed_Shield",stats:"Def: 40",source:"Inquisition"},weapon:{name:"Mycological Bow",img:"Mycological_Bow",stats:"Range: 6, Atk: 52",source:"Market"},ring:{name:"Ring of Healing",img:"Ring_of_Healing",stats:"+2 HP/turn",source:"NPC"},amulet:{name:"Amulet of Loss",img:"Amulet_of_Loss",stats:"No death penalty",source:"NPC"}},
"100-150":{helmet:{name:"Zaoan Helmet",img:"Zaoan_Helmet",stats:"Arm: 9, Dist +2",source:"Lizard City"},armor:{name:"Prismatic Armor",img:"Prismatic_Armor",stats:"Arm: 16, Phys 5%",source:"Market"},legs:{name:"Zaoan Legs",img:"Zaoan_Legs",stats:"Arm: 9",source:"Lizard City"},boots:{name:"Guardian Boots",img:"Guardian_Boots",stats:"Arm: 3, Speed +4",source:"Market"},shield:{name:"Ornate Shield",img:"Ornate_Shield",stats:"Def: 38",source:"Market"},weapon:{name:"Rift Bow",img:"Rift_Bow",stats:"Atk: 54, Dist +2",source:"Roshamuul"},ring:{name:"Prismatic Ring",img:"Prismatic_Ring",stats:"Phys prot 5%",source:"Market"},amulet:{name:"Foxtail Amulet",img:"Foxtail_Amulet",stats:"+4 Speed",source:"Were creatures"}},
"150-200":{helmet:{name:"Cobra Hood",img:"Cobra_Hood",stats:"Arm: 10, Dist +2",source:"Cobra Bastion"},armor:{name:"Prismatic Armor",img:"Prismatic_Armor",stats:"Arm: 16",source:"Market"},legs:{name:"Ornate Legs",img:"Ornate_Legs",stats:"Arm: 10",source:"Oramond"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Speed +10",source:"Dream Courts"},shield:{name:"Ornate Shield",img:"Ornate_Shield",stats:"Def: 38",source:"Market"},weapon:{name:"Bow of Destruction",img:"Bow_of_Destruction",stats:"Atk: 56, Dist +3",source:"Ferumbras"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Enchanted Theurgic Amulet",img:"Enchanted_Theurgic_Amulet",stats:"Phys 2%, ML +2",source:"Forgotten Knowledge"}},
"200-300":{helmet:{name:"Falcon Coif",img:"Falcon_Coif",stats:"Arm: 11, Dist +3",source:"Falcon Bastion"},armor:{name:"Falcon Plate",img:"Falcon_Plate",stats:"Arm: 17, Dist +3",source:"Falcon Bastion"},legs:{name:"Fabulous Legs",img:"Fabulous_Legs",stats:"Arm: 10, Speed +12",source:"Secret Library"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Speed +10",source:"Dream Courts"},shield:{name:"Falcon Shield",img:"Falcon_Shield",stats:"Def: 41",source:"Falcon Bastion"},weapon:{name:"Falcon Bow",img:"Falcon_Bow",stats:"Atk: 57, Dist +4",source:"Falcon Bastion"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Enchanted Theurgic Amulet",img:"Enchanted_Theurgic_Amulet",stats:"Phys 2%, ML +2",source:"Forgotten Knowledge"}},
"300+":{helmet:{name:"Falcon Coif",img:"Falcon_Coif",stats:"Arm: 11, Dist +3",source:"Falcon Bastion"},armor:{name:"Soulmantle",img:"Soulmantle",stats:"Arm: 18, Dist +4",source:"Soul War"},legs:{name:"Soulstrider",img:"Soulstrider",stats:"Arm: 11, Speed +15",source:"Soul War"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Speed +10",source:"Dream Courts"},shield:{name:"Soulbastion",img:"Soulbastion",stats:"Def: 42",source:"Soul War"},weapon:{name:"Soulpiercer",img:"Soulpiercer",stats:"Atk: 58, Dist +4",source:"Soul War"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Enchanted Theurgic Amulet",img:"Enchanted_Theurgic_Amulet",stats:"Phys 2%, ML +2",source:"Forgotten Knowledge"}}
},
sorcerer:{
"8-30":{helmet:{name:"Magician's Hat",img:"Magician's_Hat",stats:"Arm: 2, ML +1",source:"NPC"},armor:{name:"Blue Robe",img:"Blue_Robe",stats:"Arm: 11, ML +1",source:"Dragon Lords"},legs:{name:"Plate Legs",img:"Plate_Legs",stats:"Arm: 7",source:"Various"},boots:{name:"Sandals",img:"Sandals",stats:"Arm: 1",source:"NPC"},shield:{name:"Spellbook of Mind Control",img:"Spellbook_of_Mind_Control",stats:"ML +1",source:"NPC"},weapon:{name:"Wand of Dragonbreath",img:"Wand_of_Dragonbreath",stats:"Fire: 13",source:"NPC"},ring:{name:"Life Ring",img:"Life_Ring",stats:"+1 HP/turn",source:"NPC"},amulet:{name:"Protection Amulet",img:"Protection_Amulet",stats:"Phys prot 6%",source:"NPC"}},
"30-60":{helmet:{name:"Magician's Hat",img:"Magician's_Hat",stats:"Arm: 2, ML +1",source:"NPC"},armor:{name:"Blue Robe",img:"Blue_Robe",stats:"Arm: 11, ML +1",source:"Dragon Lords"},legs:{name:"Crown Legs",img:"Crown_Legs",stats:"Arm: 9",source:"Quest"},boots:{name:"Boots of Haste",img:"Boots_of_Haste",stats:"Speed +20",source:"Dragon Lords"},shield:{name:"Spellbook of Warding",img:"Spellbook_of_Warding",stats:"ML +2",source:"Market"},weapon:{name:"Wand of Inferno",img:"Wand_of_Inferno",stats:"Fire: 56",source:"NPC"},ring:{name:"Energy Ring",img:"Energy_Ring",stats:"Mana Shield",source:"NPC"},amulet:{name:"Platinum Amulet",img:"Platinum_Amulet",stats:"Phys prot 4%",source:"NPC"}},
"60-100":{helmet:{name:"Yalahari Mask",img:"Yalahari_Mask",stats:"Arm: 5, ML +2",source:"Yalahar Quest"},armor:{name:"Master Archer's Armor",img:"Master_Archer's_Armor",stats:"Arm: 14, ML +3",source:"Market"},legs:{name:"Golden Legs",img:"Golden_Legs",stats:"Arm: 9",source:"Annihilator"},boots:{name:"Boots of Haste",img:"Boots_of_Haste",stats:"Speed +20",source:"Dragon Lords"},shield:{name:"Spellbook of Dark Mysteries",img:"Spellbook_of_Dark_Mysteries",stats:"ML +3",source:"Market"},weapon:{name:"Wand of Defiance",img:"Wand_of_Defiance",stats:"Fire: 85",source:"NPC"},ring:{name:"Ring of Healing",img:"Ring_of_Healing",stats:"+2 HP/turn",source:"NPC"},amulet:{name:"Amulet of Loss",img:"Amulet_of_Loss",stats:"No death penalty",source:"NPC"}},
"100-150":{helmet:{name:"Yalahari Mask",img:"Yalahari_Mask",stats:"Arm: 5, ML +2",source:"Yalahar Quest"},armor:{name:"Gill Coat",img:"Gill_Coat",stats:"Arm: 15, ML +2",source:"Market"},legs:{name:"Zaoan Legs",img:"Zaoan_Legs",stats:"Arm: 9",source:"Lizard City"},boots:{name:"Pair of Soft Boots",img:"Pair_of_Soft_Boots",stats:"+HP/MP regen",source:"Market"},shield:{name:"Spellbook of Dark Mysteries",img:"Spellbook_of_Dark_Mysteries",stats:"ML +3",source:"Market"},weapon:{name:"Wand of Everblazing",img:"Wand_of_Everblazing",stats:"Fire: 86",source:"Roshamuul"},ring:{name:"Prismatic Ring",img:"Prismatic_Ring",stats:"Phys prot 5%",source:"Market"},amulet:{name:"Foxtail Amulet",img:"Foxtail_Amulet",stats:"+4 Speed",source:"Were creatures"}},
"150-200":{helmet:{name:"Cobra Hood",img:"Cobra_Hood",stats:"Arm: 10, ML +2",source:"Cobra Bastion"},armor:{name:"Gill Coat",img:"Gill_Coat",stats:"Arm: 15, ML +2",source:"Market"},legs:{name:"Ornate Legs",img:"Ornate_Legs",stats:"Arm: 10",source:"Oramond"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Speed +10",source:"Dream Courts"},shield:{name:"Spellbook of Dark Mysteries",img:"Spellbook_of_Dark_Mysteries",stats:"ML +3",source:"Market"},weapon:{name:"Wand of Destruction",img:"Wand_of_Destruction",stats:"Fire: 90",source:"Ferumbras"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Enchanted Theurgic Amulet",img:"Enchanted_Theurgic_Amulet",stats:"Phys 2%, ML +2",source:"Forgotten Knowledge"}},
"200-300":{helmet:{name:"Falcon Coif",img:"Falcon_Coif",stats:"Arm: 11, ML +3",source:"Falcon Bastion"},armor:{name:"Falcon Plate",img:"Falcon_Plate",stats:"Arm: 17, ML +3",source:"Falcon Bastion"},legs:{name:"Fabulous Legs",img:"Fabulous_Legs",stats:"Arm: 10, Speed +12",source:"Secret Library"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Speed +10",source:"Dream Courts"},shield:{name:"Falcon Escutcheon",img:"Falcon_Escutcheon",stats:"ML +3",source:"Falcon Bastion"},weapon:{name:"Falcon Wand",img:"Falcon_Wand",stats:"Fire: 92, ML +3",source:"Falcon Bastion"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Enchanted Theurgic Amulet",img:"Enchanted_Theurgic_Amulet",stats:"Phys 2%, ML +2",source:"Forgotten Knowledge"}},
"300+":{helmet:{name:"Falcon Coif",img:"Falcon_Coif",stats:"Arm: 11, ML +3",source:"Falcon Bastion"},armor:{name:"Soulmantle",img:"Soulmantle",stats:"Arm: 18, ML +4",source:"Soul War"},legs:{name:"Soulstrider",img:"Soulstrider",stats:"Arm: 11, Speed +15",source:"Soul War"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Speed +10",source:"Dream Courts"},shield:{name:"Soulbastion",img:"Soulbastion",stats:"ML +4",source:"Soul War"},weapon:{name:"Soultainter",img:"Soultainter",stats:"Fire: 94, ML +4",source:"Soul War"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Enchanted Theurgic Amulet",img:"Enchanted_Theurgic_Amulet",stats:"Phys 2%, ML +2",source:"Forgotten Knowledge"}}
},
druid:{
"8-30":{helmet:{name:"Magician's Hat",img:"Magician's_Hat",stats:"Arm: 2, ML +1",source:"NPC"},armor:{name:"Blue Robe",img:"Blue_Robe",stats:"Arm: 11, ML +1",source:"Dragon Lords"},legs:{name:"Plate Legs",img:"Plate_Legs",stats:"Arm: 7",source:"Various"},boots:{name:"Sandals",img:"Sandals",stats:"Arm: 1",source:"NPC"},shield:{name:"Spellbook of Mind Control",img:"Spellbook_of_Mind_Control",stats:"ML +1",source:"NPC"},weapon:{name:"Hailstorm Rod",img:"Hailstorm_Rod",stats:"Ice: 13",source:"NPC"},ring:{name:"Life Ring",img:"Life_Ring",stats:"+1 HP/turn",source:"NPC"},amulet:{name:"Protection Amulet",img:"Protection_Amulet",stats:"Phys prot 6%",source:"NPC"}},
"30-60":{helmet:{name:"Magician's Hat",img:"Magician's_Hat",stats:"Arm: 2, ML +1",source:"NPC"},armor:{name:"Blue Robe",img:"Blue_Robe",stats:"Arm: 11, ML +1",source:"Dragon Lords"},legs:{name:"Crown Legs",img:"Crown_Legs",stats:"Arm: 9",source:"Quest"},boots:{name:"Boots of Haste",img:"Boots_of_Haste",stats:"Speed +20",source:"Dragon Lords"},shield:{name:"Spellbook of Warding",img:"Spellbook_of_Warding",stats:"ML +2",source:"Market"},weapon:{name:"Underworld Rod",img:"Underworld_Rod",stats:"Death: 56",source:"NPC"},ring:{name:"Energy Ring",img:"Energy_Ring",stats:"Mana Shield",source:"NPC"},amulet:{name:"Platinum Amulet",img:"Platinum_Amulet",stats:"Phys prot 4%",source:"NPC"}},
"60-100":{helmet:{name:"Yalahari Mask",img:"Yalahari_Mask",stats:"Arm: 5, ML +2",source:"Yalahar Quest"},armor:{name:"Master Archer's Armor",img:"Master_Archer's_Armor",stats:"Arm: 14, ML +3",source:"Market"},legs:{name:"Golden Legs",img:"Golden_Legs",stats:"Arm: 9",source:"Annihilator"},boots:{name:"Boots of Haste",img:"Boots_of_Haste",stats:"Speed +20",source:"Dragon Lords"},shield:{name:"Spellbook of Dark Mysteries",img:"Spellbook_of_Dark_Mysteries",stats:"ML +3",source:"Market"},weapon:{name:"Deepling Staff",img:"Deepling_Staff",stats:"Ice: 85",source:"NPC"},ring:{name:"Ring of Healing",img:"Ring_of_Healing",stats:"+2 HP/turn",source:"NPC"},amulet:{name:"Amulet of Loss",img:"Amulet_of_Loss",stats:"No death penalty",source:"NPC"}},
"100-150":{helmet:{name:"Yalahari Mask",img:"Yalahari_Mask",stats:"Arm: 5, ML +2",source:"Yalahar Quest"},armor:{name:"Gill Coat",img:"Gill_Coat",stats:"Arm: 15, ML +2",source:"Market"},legs:{name:"Zaoan Legs",img:"Zaoan_Legs",stats:"Arm: 9",source:"Lizard City"},boots:{name:"Pair of Soft Boots",img:"Pair_of_Soft_Boots",stats:"+HP/MP regen",source:"Market"},shield:{name:"Spellbook of Dark Mysteries",img:"Spellbook_of_Dark_Mysteries",stats:"ML +3",source:"Market"},weapon:{name:"Rod of Destruction",img:"Rod_of_Destruction",stats:"Ice: 90",source:"Ferumbras"},ring:{name:"Prismatic Ring",img:"Prismatic_Ring",stats:"Phys prot 5%",source:"Market"},amulet:{name:"Foxtail Amulet",img:"Foxtail_Amulet",stats:"+4 Speed",source:"Were creatures"}},
"150-200":{helmet:{name:"Cobra Hood",img:"Cobra_Hood",stats:"Arm: 10, ML +2",source:"Cobra Bastion"},armor:{name:"Gill Coat",img:"Gill_Coat",stats:"Arm: 15, ML +2",source:"Market"},legs:{name:"Ornate Legs",img:"Ornate_Legs",stats:"Arm: 10",source:"Oramond"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Speed +10",source:"Dream Courts"},shield:{name:"Spellbook of Dark Mysteries",img:"Spellbook_of_Dark_Mysteries",stats:"ML +3",source:"Market"},weapon:{name:"Rod of Destruction",img:"Rod_of_Destruction",stats:"Ice: 90",source:"Ferumbras"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Enchanted Theurgic Amulet",img:"Enchanted_Theurgic_Amulet",stats:"Phys 2%, ML +2",source:"Forgotten Knowledge"}},
"200-300":{helmet:{name:"Falcon Coif",img:"Falcon_Coif",stats:"Arm: 11, ML +3",source:"Falcon Bastion"},armor:{name:"Falcon Plate",img:"Falcon_Plate",stats:"Arm: 17, ML +3",source:"Falcon Bastion"},legs:{name:"Fabulous Legs",img:"Fabulous_Legs",stats:"Arm: 10, Speed +12",source:"Secret Library"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Speed +10",source:"Dream Courts"},shield:{name:"Falcon Escutcheon",img:"Falcon_Escutcheon",stats:"ML +3",source:"Falcon Bastion"},weapon:{name:"Falcon Rod",img:"Falcon_Rod",stats:"Ice: 92, ML +3",source:"Falcon Bastion"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Enchanted Theurgic Amulet",img:"Enchanted_Theurgic_Amulet",stats:"Phys 2%, ML +2",source:"Forgotten Knowledge"}},
"300+":{helmet:{name:"Falcon Coif",img:"Falcon_Coif",stats:"Arm: 11, ML +3",source:"Falcon Bastion"},armor:{name:"Soulmantle",img:"Soulmantle",stats:"Arm: 18, ML +4",source:"Soul War"},legs:{name:"Soulstrider",img:"Soulstrider",stats:"Arm: 11, Speed +15",source:"Soul War"},boots:{name:"Pair of Dreamwalkers",img:"Pair_of_Dreamwalkers",stats:"Speed +10",source:"Dream Courts"},shield:{name:"Soulbastion",img:"Soulbastion",stats:"ML +4",source:"Soul War"},weapon:{name:"Soultainter",img:"Soultainter",stats:"Ice: 94, ML +4",source:"Soul War"},ring:{name:"Ring of Blue Plasma",img:"Ring_of_Blue_Plasma",stats:"+2 ML",source:"Gnomprona"},amulet:{name:"Enchanted Theurgic Amulet",img:"Enchanted_Theurgic_Amulet",stats:"Phys 2%, ML +2",source:"Forgotten Knowledge"}}
}
};

// ================================================================
// QUESTS DATA (abbreviated - full walkthroughs in previous version preserved)
// The quest data structure stays the same as in the embedded version
// but we keep it in this separate file for maintainability
// ================================================================
const QUESTS = [
{name:"The Desert Dungeon Quest",level:0,premium:false,location:"Ankrahmun",npc:"—",desc:"Explore the crypt systems beneath Ankrahmun's desert sands. Multiple treasure rooms with decent loot for free account players.",requirements:["Rope","Shovel"],steps:["Travel to Ankrahmun, head east into the desert.","Find the hole in the sand, use shovel to dig down.","Navigate underground tunnels heading south.","Use rope to cross gaps and reach treasure rooms.","Open chests to collect rewards."],rewards:["Silver Brooch","Green Gem","150 gold"],dangers:["Skeleton","Ghoul","Mummy"],tips:"Bring health potions. Watch for poison fields."},
{name:"The Paradox Tower Quest",level:30,premium:true,location:"Edron",npc:"Spectulus",desc:"Climb the Paradox Tower by solving riddles from the Mad Mage. Each floor has a unique puzzle. One of Tibia's most iconic quests.",requirements:["200 gold","Rope","Level 30+"],steps:["Find the Paradox Tower northeast of Edron depot.","Enter and talk to the first NPC.","Answer the riddle correctly (relates to Tibia lore).","Second floor: solve the mathematical puzzle.","Third floor: use convince creature rune on the specific creature.","Fourth floor: navigate the maze (N, E, S, W, N).","Top floor: claim reward from chest."],rewards:["Wand of Cosmic Energy","3,000 exp"],dangers:["None (puzzle-based)"],tips:"Write down riddle answers. Each floor requires a different approach."},
{name:"The Djinn War Quest",level:40,premium:true,location:"Ankrahmun / Drefia",npc:"Fa'hradin / Malor",desc:"Choose between Marid (Blue Djinn) and Efreet (Green Djinn) factions. PERMANENT choice that unlocks the best NPC trade prices.",requirements:["Blue/Green Piece of Cloth","10,000 gold"],steps:["Travel to Ankrahmun, decide your faction.","Blue: Go to Blue Djinn Fortress south of Ab'Dendriel.","Green: Go to Green Djinn Tower near Drefia.","Complete 3 faction missions — retrieve artifacts, deliver messages, kill bosses.","Talk to faction leader for permanent NPC access."],rewards:["Blue/Green Djinn NPC trade access","Best prices for rare items"],dangers:["Efreet","Marid","Djinns"],tips:"PERMANENT choice! Blue Djinns buy creature products at best prices. Most players choose Blue."},
{name:"Pits of Inferno Quest",level:100,premium:true,location:"Edron / PoI",npc:"Hugo",desc:"Navigate 7 throne rooms representing deadly sins. Requires a full team of 4+ experienced players. One of Tibia's hardest classic quests.",requirements:["Blessed Wooden Stake","Holy Water","Level 100+","Full team (EK+ED+MS+RP)"],steps:["Form team of 4+ experienced players.","Enter through Edron's Hero Cave, go deeper.","Navigate initial tunnels to 7 throne rooms.","Throne 1 (Greed): Fight demons, collect Gem.","Throne 2-6: Each has unique mechanics — creatures, puzzles, mazes.","Throne 7 (Pride): Defeat final guardians.","Use all 7 gems to access reward room.","Choose ONE reward item."],rewards:["Arbalest","Soft Boots","Backpack of Holding","Stuffed Dragon"],dangers:["Demons","Juggernauts","Hellhounds","Destroyers"],tips:"Knight should be 120+ for comfortable blocking. Bring massive supplies."},
{name:"The Inquisition Quest",level:100,premium:true,location:"Multiple cities",npc:"Henricus",desc:"Join the Inquisition to fight evil. Massive questline with increasingly difficult bosses across multiple cities.",requirements:["Level 100+","Team of 5+"],steps:["Talk to Henricus in Thais temple.","Complete 4 investigation missions across cities.","Mission 5: Boss — Ushuriel (bring Energy protection).","Mission 6: Boss — Zugurosh (bring Fire protection).","Mission 7: Boss — Madareth (bring Earth protection).","Mission 8: Boss — Annihilon (bring full team).","Talk to Henricus for reward choice."],rewards:["Blessed Shield (Def 40)","Emerald Sword","Boss access"],dangers:["Ushuriel","Zugurosh","Madareth","Annihilon"],tips:"Each boss needs different elemental protection. Blessed Shield is best reward for knights."},
{name:"Wrath of the Emperor Quest",level:100,premium:true,location:"Zao",npc:"Emperor Kruzak",desc:"Infiltrate enemy lizard lines on Zao. Unlocks deep Zao content including Draken Walls hunting.",requirements:["Level 100+","New Frontier + Children of Revolution completed"],steps:["Talk to Emperor Kruzak in Zao's dragon stronghold.","Infiltrate the Lizard Chosen camp, steal documents.","Navigate muggy plains avoiding patrols.","Enter Dragon Palace, complete 3 internal missions.","Fight through Draken Walls to inner sanctum.","Defeat Lizard High Commander.","Return to Kruzak."],rewards:["Helmet of the Deep","Full Zao access","15,000 exp"],dangers:["Draken Spellweaver","Draken Elite","Lizard Chosen"],tips:"Fire protection for Draken Spellweavers. Unlocks top-tier hunting spots."},
{name:"In Service of Yalahar Quest",level:80,premium:true,location:"Yalahar",npc:"Palimuth",desc:"Explore and restore Yalahar's quarters. Multi-chapter quest with unique boss fights. Rewards the Yalahari Mask (ML +2).",requirements:["Level 80+","Rope","Shovel"],steps:["Arrive in Yalahar, talk to Palimuth.","Explore and fix Trade Quarter.","Clear Cemetery Quarter of undead.","Neutralize Alchemist Quarter mutations.","Resolve Foreign Quarter diplomacy.","Investigate Sunken Quarter (underwater).","Face Magician Quarter challenge.","Return to Palimuth for rewards."],rewards:["Yalahari Mask (ML +2)","Yalahari Leg Piece","Full Yalahar access"],dangers:["Mutated creatures","Vampires","Demons"],tips:"Yalahari Mask is best-in-slot for mages until 150+. Complete in order."},
{name:"The Annihilator Quest",level:100,premium:false,location:"Near Venore",npc:"—",desc:"THE classic 4-player quest. Face 6 Demons simultaneously in a tiny room. Perfect teamwork required.",requirements:["Exactly 4 players","Level 100+","Key 3600"],steps:["Form team of exactly 4 players (EK+ED+MS+RP ideal).","Travel to entrance southeast of Venore.","All 4 step on tiles simultaneously to open door.","Fight 6 Demons in a small room.","Knight blocks all 6, Druid heals with exura sio.","Sorcerer and Paladin deal damage.","Survive until all Demons dead.","Each player opens one of 4 reward chests."],rewards:["Demon Armor","Magic Plate Armor","Stonecutter Axe","Golden Legs"],dangers:["6 Demons simultaneously"],tips:"Knight MUST tank all 6. Druid spams exura sio. Pre-buff with utamo vita. Legendary quest."},
{name:"Forgotten Knowledge Quest",level:250,premium:true,location:"Multiple",npc:"Various",desc:"Fight powerful bosses to earn the Enchanted Theurgic Amulet — best-in-slot amulet for all vocations at high levels.",requirements:["Level 250+","Team of 10+","Multiple access quests"],steps:["Complete prerequisite quests for each boss location.","Boss 1: The Last Lore Keeper — ice protection.","Boss 2: Lloyd — energy protection.","Boss 3: The Sandking — earth protection.","Boss 4: Thorn Knight — physical protection.","Collect components from all bosses.","Combine to create Enchanted Theurgic Amulet."],rewards:["Enchanted Theurgic Amulet (Phys 2%, ML +2)"],dangers:["The Last Lore Keeper","Lloyd","The Sandking"],tips:"Best-in-slot amulet for ALL vocations at high levels. Worth the grind."},
{name:"Ferumbras' Ascension Quest",level:250,premium:true,location:"Edron",npc:"Mazarius",desc:"Stop Ferumbras from ascending. Hardest bosses in classic Tibia. Drops Destruction-tier weapons.",requirements:["Level 250+","Large team (20+)"],steps:["Talk to Mazarius in Edron.","Clear the Ascendant Tower entrance.","Complete 3 mini-boss rooms.","Fight through Hellflayers, Vexclaws, Grimeleeches.","Defeat Ferumbras Mortal Shell (main boss).","Access reward room, choose weapon."],rewards:["Blade/Bow/Wand/Rod of Destruction"],dangers:["Hellflayer","Vexclaw","Grimeleech","Ferumbras Mortal Shell"],tips:"Destruction weapons are best until Falcon/Soul tier. Massive supplies needed."},
{name:"Secret Library Quest",level:250,premium:true,location:"Multiple",npc:"Spectulus",desc:"Explore hidden library dimensions. Unlocks one of the best XP hunting areas in the game.",requirements:["Level 250+","Team for bosses"],steps:["Talk to Spectulus in Edron.","Complete access missions for each wing.","Clear Fire Wing (Burning Books, fire enemies).","Clear Ice Wing (Icecold Books, frost enemies).","Clear Energy Wing (Energized Raging Mages).","Defeat each wing boss.","Access final reward room."],rewards:["Fabulous Legs (Arm 10, Speed +12)","Library hunting access"],dangers:["Burning Book","Icecold Book","Energized Raging Mage"],tips:"Library = best XP/h for 300+. Fabulous Legs are excellent for all vocations."},
{name:"Soul War Quest",level:250,premium:true,location:"Feyrist / Zarganash",npc:"Spectulus",desc:"THE pinnacle of Tibia endgame. Enter the realm between life and death. Best-in-slot equipment for all vocations.",requirements:["Level 250+","Team of 30+","Many prerequisite quests"],steps:["Complete all prerequisite quests.","Enter Zarganash through Feyrist portal.","Navigate soul planes fighting powerful enemies.","Complete 5 tainting levels for boss access.","Boss 1: Goshnar's Cruelty — all protections.","Boss 2: Goshnar's Hatred — coordinate positions.","Boss 3: Goshnar's Malice — DPS race.","Boss 4: Goshnar's Spite — heal through AoE.","Boss 5: Goshnar's Megalomania — final boss, perfect teamwork.","Collect soul tokens, exchange for equipment."],rewards:["Soulmantle (Arm 18)","Soulstrider (Speed +15)","Soulbastion (Def 42)","Soulcutter/Soulpiercer/Soultainter"],dangers:["Goshnar's Cruelty","Goshnar's Megalomania"],tips:"Soul = best-in-slot for ALL vocations. Requires months of preparation and a dedicated team."},
{name:"Grave Danger Quest",level:250,premium:true,location:"Multiple",npc:"Investigator",desc:"Investigate undead lords. Unlocks Falcon equipment — second-best tier in game. Falcon Bastion is top hunting spot.",requirements:["Level 250+","Team of 15+"],steps:["Talk to Investigator to start questline.","Investigate 4 undead activity locations.","Fight through Falcon Knights and Paladins.","Defeat King Zelos and lieutenants.","Defeat Grand Master Oberon (final boss).","Collect Falcon equipment from drops."],rewards:["Falcon equipment access","Falcon Bastion hunting"],dangers:["Falcon Knight","Falcon Paladin","Grand Master Oberon"],tips:"Falcon equipment = second-best tier. Bastion is excellent hunting 300+."},
{name:"Killing in the Name of...",level:0,premium:true,location:"Port Hope",npc:"Grizzly Adams",desc:"Repeatable hunting task system. Hunt creatures for points and unlock rewards. Best daily income system.",requirements:["Varies by task"],steps:["Talk to Grizzly Adams in Port Hope.","Choose creature task from available options.","Hunt required number (300-6000 creatures).","Return to turn in task.","Accumulate points for rewards and boss access."],rewards:["Task points","Outfit addons","Boss access"],dangers:["Varies"],tips:"Overlap tasks with normal hunting for efficiency."},
{name:"Oramond Quest",level:80,premium:true,location:"Rathleton",npc:"Jondrin",desc:"Unlock Oramond hunting grounds including the BEST PROFIT spot in the game — Oramond Minos.",requirements:["Level 80+ (200+ for Minos)"],steps:["Sail to Rathleton, talk to Jondrin.","Complete tasks to earn reputation.","Unlock hunting ground access.","Complete 40 daily tasks for Mino access.","Optional: Unlock Glooth Bandit area."],rewards:["Oramond access","Mino hunting (BEST profit)"],dangers:["Glooth creatures","Minotaur Amazons"],tips:"40 daily tasks for Minos is 100% worth it. Best gold/hour in game at 200+."},
{name:"A Threatened Dream Quest",level:150,premium:true,location:"Feyrist",npc:"Fauns",desc:"Enter Feyrist dream realm. Unlocks beautiful hunting areas for 150-250 range. Prerequisite for Dream Courts.",requirements:["Level 150+"],steps:["Find Feyrist portal near Carlin/Ab'Dendriel.","Talk to Faun guardian.","Complete 3 purification rituals.","Fight corrupted Dream creatures.","Defeat Dream Court bosses."],rewards:["Feyrist access","Dream equipment"],dangers:["Boar Man","Dark Faun","Twisted Pooka"],tips:"Feyrist = best hunting for 150-250. Dream equipment is excellent."},
{name:"The Dream Courts Quest",level:200,premium:true,location:"Feyrist",npc:"Court NPCs",desc:"Challenge dream rulers for the coveted Pair of Dreamwalkers — best-in-slot boots for most vocations.",requirements:["Level 200+","A Threatened Dream completed","Team of 10+"],steps:["Enter Dream Courts through Feyrist.","Complete Summer and Winter Court trials.","Defeat Dream Court bosses.","Challenge Maxxenius (ultimate dream boss).","Collect tokens for Dreamwalker boots."],rewards:["Pair of Dreamwalkers (Speed +10)"],dangers:["Court bosses","Maxxenius"],tips:"Dreamwalkers = best-in-slot boots at high levels."},
{name:"Cobra Bastion Quest",level:250,premium:true,location:"Issavi",npc:"Scarlett Etzel",desc:"Infiltrate the Cobra Bastion. Drops Cobra Hood — best-in-slot helmet for mages 150-250.",requirements:["Level 250+","Team of 10+","Kilmaresh access"],steps:["Travel to Issavi.","Talk to Scarlett Etzel.","Navigate Cobra Bastion's 3 levels.","Defeat Cobra commanders.","Face final boss."],rewards:["Cobra Hood (Arm 10, ML +2)","Cobra equipment"],dangers:["Cobra Assassin","Cobra Scout","Cobra Vizier"],tips:"Cobra Hood = best helmet for mages 150-250."},
{name:"Roshamuul Quest",level:200,premium:true,location:"Roshamuul",npc:"A Bloodbeast",desc:"Access demon-infested prison island. Unlocks Guzzlemaw Valley — top-tier XP for 250+ teams.",requirements:["Level 200+"],steps:["Sail to Roshamuul.","Navigate dangerous terrain.","Complete access missions.","Clear first prison level.","Unlock Guzzlemaw Valley."],rewards:["Roshamuul access","Guzzlemaw Valley"],dangers:["Guzzlemaw","Frazzlemaw","Silencer"],tips:"Guzzlemaw Valley = top XP for 250+ teams."},
{name:"Adventurer's Guild Quest",level:0,premium:false,location:"Thais",npc:"Guild NPCs",desc:"Join the Adventurer's Guild for daily reward shrine access. Do this ASAP — daily rewards accumulate and are very valuable.",requirements:["None"],steps:["Find Adventurer's Guild in south Thais.","Talk to guild leader.","Complete simple initiation.","Use daily reward shrines worldwide."],rewards:["Daily reward shrine access"],dangers:["None"],tips:"Do this IMMEDIATELY on any new character. Daily rewards stack up."}
];
